FROM golang:1.25-alpine as builder

ADD . /app
WORKDIR /app

RUN go mod download && go mod verify

RUN go build  -o ./app ./cmd

FROM alpine:3.14

RUN mkdir /app
WORKDIR /app

COPY --from=builder --chown=app:app /app/app .
COPY --from=builder --chown=app:app /app/db/ db/
COPY --from=builder --chown=app:app /app/config/ config/

CMD ["./app" ]